export class UserRegistration {
  webSelectors = {
    registerLink: ".ico-register",
    maleGender: "#gender-male",
    femaleGender: "#gender-female",
    firstName: "#FirstName",
    lastName: "#LastName",
    day: "select[name='DateOfBirthDay']",
    month: "select[name='DateOfBirthMonth']",
    year: "select[name='DateOfBirthYear']",
    email: "#Email",
    userName: "#Username",
    address: "#StreetAddress",
    postal_code: "#ZipPostalCode",
    country: "#County",
    city: "#City",
    state: "#StateProvinceId",
    password: "#Password",
    confirmPwd: "#ConfirmPassword",
    privatePolicy: "#accept-consent",
    register: "#register-button",
  };

  pageAction = {
    clickRegisterLink: () => cy.get(this.webSelectors.registerLink),
    selectMaleGender: () => cy.get(this.webSelectors.maleGender),
    selectFemaleGender: () => cy.get(this.webSelectors.femaleGender),
    enterFirstName: () => cy.get(this.webSelectors.firstName),
    enterLastName: () => cy.get(this.webSelectors.lastName),
    selectDay: () => cy.get(this.webSelectors.day),
    selectMonth: () => cy.get(this.webSelectors.month),
    selectYear: () => cy.get(this.webSelectors.year),
    enterEmail: () => cy.get(this.webSelectors.email),
    enterUsername: () => cy.get(this.webSelectors.userName),
    enterAddress: () => cy.get(this.webSelectors.address),
    enterZip: () => cy.get(this.webSelectors.postal_code),
    entercountry: () => cy.get(this.webSelectors.country),
    enterCity: () => cy.get(this.webSelectors.city),
    selectState: () => cy.get(this.webSelectors.state),
    enterPassword: () => cy.get(this.webSelectors.password),
    enterconfirmPwd: () => cy.get(this.webSelectors.confirmPwd),
    clickPP: () => cy.get(this.webSelectors.privatePolicy),
    clickRegisterBtn: () => cy.get(this.webSelectors.register),
  };
}
